# This is a basic workflow to help you get started with Actions

name: script-convenience-store_v1.0

permissions:
    contents: write

# Controls when the workflow will run
on:
    # Triggers the workflow on push or pull request events but only for the master branch
    push:
        branches: [v1.0]

    # Allows you to run this workflow manually from the Actions tab
    workflow_dispatch:

# A workflow run is made up of one or more jobs that can run sequentially or in parallel
jobs:
    # This workflow contains a single job called "build"
    build:
        # The type of runner that the job will run on
        runs-on: ubuntu-latest

        # Steps represent a sequence of tasks that will be executed as part of the job
        steps:
            - name: Checkout repo code
              uses: actions/checkout@v2
            - name: Update
              run: sudo apt update
            - name: Install Sphinx
              run: sudo apt install python3-sphinx
            - name: Install pip
              run: sudo apt install python3-pip
            - name: Install pip dependencies
              run: python3 -m pip install -r requirements.txt
            - name: Generate build with sphinx
              run: make html
            # - name: Rsync to server
            #   run: rsync -avz ./build/ ${{ secrets.SSH_USER }}@${{ secrets.SSH_HOST }}:/var/www/html/build/
            - name: Deploy to Github Production branch
              uses: JamesIves/github-pages-deploy-action@v4
              with:
                folder: build
                branch: gh-pages
